spring.application.name=BioMedic

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/phongkham_xetnghiem?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=ngannganngan

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false